name: Deploy to live

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set CI to false
        run: echo "CI=false" >> $GITHUB_ENV
        
      - name: Install dependencies
        run: npm install

      - name: Disable ESLint
        run: echo "eslint-disable" > .eslintignore

      - name: Build React application
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: stacksinfo
          channelId: live
          public: build
